version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tiempos_db
    restart: always
    environment:
      POSTGRES_USER: tiempos_user
      POSTGRES_PASSWORD: tiempos_password
      POSTGRES_DB: tiempos_db
      TZ: America/Costa_Rica
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: tiempos_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
